kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bgdk-argocd-rolebinding
  namespace: bgdk
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bgdk-user
